name: 'Deploy to AWS S3'
description: 'Deploy a static website'
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true
  region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Folder contaning deployable files'
    required: true
runs:
  using: 'node16'
  main: 'main.js'